rm -r archives
rm -r 2017
rm -r css
rm -r fonts
rm -r js
mv public/2017  2017/
mv public/archives archives/
mv public/css css/
mv public/fonts fonts/
mv public/index.html index.html
mv public/js  js/
